sockets: Drop unused variables
Otherwise I get

 | sockets.c: In function ‘dump_socket’:
 | sockets.c:467: error: ‘st.st_ino’ may be used uninitialized in this function

Signed-off-by: Cyrill Gorcunov <gorcunov@openvz.org>
Signed-off-by: Pavel Emelyanov <xemul@parallels.com>