ci: fix build on centos7 with libbsd-devel
The libbsd-devel package is an optional dependency that enables support
for setproctitle(). Building CRIU on CentOS 7 currently fails with the
following error because libbsd defines __has_include as the constant 1.

criu/include/linux/rseq.h:7:22: fatal error: sys/rseq.h: No such file or directory
 #include <sys/rseq.h>

Fixes: #2036

Signed-off-by: Radostin Stoyanov <radostin@redhat.com>