ci: require libdrm for amdgpu plugin tests
Skip testing amdgpu plugin if libdrm is not installed to
fix the following error:

make[1]: Entering directory '/tmp/criu/plugins/amdgpu'
gcc amdgpu_plugin_topology.c tests/test_topology_remap.c -o test_topology_remap -DCOMPILE_TESTS -iquote../../include -iquote../../criu/include -iquote../../criu/arch//include/ -iquote../../ -I .
In file included from amdgpu_plugin_topology.c:18:
kfd_ioctl.h:26:10: fatal error: libdrm/drm.h: No such file or directory
 #include <libdrm/drm.h>
          ^~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:39: test_topology_remap] Error 1
make[1]: Leaving directory '/tmp/criu/plugins/amdgpu'

Signed-off-by: Radostin Stoyanov <rstoyanov@fedoraproject.org>