net: libnetlink -- Add #ifdefs to escape system header conflict
Otherwise getting errors like

 | CC       libnetlink.o
 | In file included from libnetlink.c:4:0:
 | ./include/libnetlink.h:34:0: error: "NLMSG_LENGTH" redefined [-Werror]

And make macros a bit more readable.

Signed-off-by: Cyrill Gorcunov <gorcunov@openvz.org>