travis: add libcap-dev
It's required for zdtm/live/static/different_creds

cc -g -O2 -Wall -Werror -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0  -iquote ../../lib/arch/x86/include -I../../lib  -c -o different_creds.o different_creds.c
different_creds.c:7:28: fatal error: sys/capability.h: No such file or directory

Signed-off-by: Andrew Vagin <avagin@openvz.org>
Signed-off-by: Andrey Vagin <avagin@openvz.org>
Signed-off-by: Pavel Emelyanov <xemul@parallels.com>