zdtm: workaround compiling errors on ubuntu 10.4
getsid is required _XOPEN_SOURCE_EXTENDED,
it's enabled if __GNU_SOURCE is defined.

session00.c:92: error: implicit declaration of function 'getsid'

Signed-off-by: Andrew Vagin <avagin@parallels.com>
Signed-off-by: Pavel Emelyanov <xemul@parallels.com>