zdtm: consolidate pidfd definitions
Consolidate common pidfd definitions into a header file and define
missing `__NR_pidfd_open` and `__NR_pidfd_getfd` to fix the following
build errors on AlmaLinux 8:

../lib/pidfd.h:16:17: error: ‘__NR_pidfd_getfd’ undeclared (first use in this function); did you mean ‘pidfd_getfd’?
  return syscall(__NR_pidfd_getfd, pidfd, targetfd, flags);
                 ^~~~~~~~~~~~~~~~
                 pidfd_getfd

pidfd_of_thread.c: In function ‘pidfd_open’:
pidfd_of_thread.c:38:17: error: ‘__NR_pidfd_open’ undeclared (first use in this function); did you mean ‘pidfd_open’?
  return syscall(__NR_pidfd_open, pid, flags);
		 ^~~~~~~~~~~~~~~
		 pidfd_open

In addition, add *.desc files for the pidfd tests so that these
tests are skipped if the kernel does not support pidfd.

Signed-off-by: Radostin Stoyanov <rstoyanov@fedoraproject.org>