Make sure sed fixups are carried out
The following issue is possibly caused by using busybox make.

protobuf/packet-sock.pb-c.c: In function 'packet_sock_entry__init':
protobuf/packet-sock.pb-c.c:98:3: error: this decimal constant is unsigned only in ISO C90 [-Werror]

Use a belt-and-suspenders approach to ensure it doesn't happen.

Signed-off-by: Pavel Emelyanov <xemul@parallels.com>