image.h: Include fcntl.h
No all distros (Rpi) provide O_PATH definition,
so include fcntl.h here thus we don't hit compilation
problem like

 |  CC       image.o
 | image.c: In function ‘open_image_at’:
 | image.c:187:29: error: ‘O_PATH’ undeclared (first use in this function)

Reported-by: Pavel Emelyanov <xemul@parallels.com>
Signed-off-by: Cyrill Gorcunov <gorcunov@openvz.org>
Signed-off-by: Pavel Emelyanov <xemul@parallels.com>