zdtm/tun_ns: add per-test dependencies
The tun_ns test was introduced with [1] and [2], however, these commits
didn't add per-test dependencies required for the test.

Per-test dependencies are listed in the .desc file as 'deps': [<list>]

These dependencies are made available inside the test namespace and without
the ip dependency, the tests fails on Fedora 34 with

   Error: ipv4: FIB table does not exist.

[1] https://github.com/checkpoint-restore/criu/commit/7e355e7
[2] https://github.com/checkpoint-restore/criu/commit/3ba0893

Signed-off-by: Radostin Stoyanov <rstoyanov@fedoraproject.org>