ptrace.h: move PTRACE_{GET,SET}SIGMASK under ifdef
In glibc 2.23 PTRACE_{GET,SET}SIGMASK are defined at <ptrace.h>:
http://fossies.org/diffs/glibc/2.22_vs_2.23/sysdeps/unix/sysv/linux/powerpc/sys/ptrace.h-diff.html

Move them under ifdef to fix the following errors:
In file included from arch/x86/crtools.c:14:0:
~/tools/criu/criu/include/ptrace.h:47:0: error: "PTRACE_GETSIGMASK" redefined [-Werror]
 #define PTRACE_GETSIGMASK 0x420a
 ^
In file included from include/ptrace.h:5:0,
                 from arch/x86/crtools.c:14:
/usr/include/sys/ptrace.h:156:0: note: this is the location of the previous definition
 #define PTRACE_GETSIGMASK PTRACE_GETSIGMASK
 ^
In file included from arch/x86/crtools.c:14:0:
~/tools/criu/criu/include/ptrace.h:48:0: error: "PTRACE_SETSIGMASK" redefined [-Werror]
 #define PTRACE_SETSIGMASK 0x420b
 ^
In file included from include/ptrace.h:5:0,
                 from arch/x86/crtools.c:14:
/usr/include/sys/ptrace.h:159:0: note: this is the location of the previous definition
 #define PTRACE_SETSIGMASK PTRACE_SETSIGMASK
 ^
cc1: all warnings being treated as errors

Fixes #119

Signed-off-by: Dmitry Safonov <dsafonov@virtuozzo.com>
Signed-off-by: Pavel Emelyanov <xemul@virtuozzo.com>